from tests.test_calls import test_get


def test_event_analysis():
    print("####################   TESTING EVENT ANALYSIS   ####################")

    # GETTING ALL USAGES
    print("TEST_1 --- GET ANALYSIS ON FAKE EVENT DATA")
    uri = "events/analyze"
    expected_result = {
        "results": [
            {"item_ids": [3, 4], "is_predicted_group_percentage": 11.52, "is_relevant_group_percentage": 13.6},
            {"item_ids": [4, 6], "is_predicted_group_percentage": 9.36, "is_relevant_group_percentage": 7.79},
            {"item_ids": [5, 6], "is_predicted_group_percentage": 15.84, "is_relevant_group_percentage": 18.81},
            {"item_ids": [4, 5], "is_predicted_group_percentage": 16.56, "is_relevant_group_percentage": 14.8},
            {"item_ids": [1, 6], "is_predicted_group_percentage": 12.24, "is_relevant_group_percentage": 11.76},
            {"item_ids": [5, 7], "is_predicted_group_percentage": 11.52, "is_relevant_group_percentage": 11.57},
            {"item_ids": [0, 3, 4, 6], "is_predicted_group_percentage": 0.72, "is_relevant_group_percentage": 0.45},
            {"item_ids": [2, 5], "is_predicted_group_percentage": 13.68, "is_relevant_group_percentage": 13.38},
            {"item_ids": [6, 7], "is_predicted_group_percentage": 12.24, "is_relevant_group_percentage": 11.23},
            {"item_ids": [1, 4, 5], "is_predicted_group_percentage": 0.72, "is_relevant_group_percentage": 1.28},
            {"item_ids": [0, 3], "is_predicted_group_percentage": 11.52, "is_relevant_group_percentage": 11.97},
            {"item_ids": [1, 4], "is_predicted_group_percentage": 18.0, "is_relevant_group_percentage": 17.25},
            {"item_ids": [4, 5, 6], "is_predicted_group_percentage": 0.72, "is_relevant_group_percentage": 0.45},
            {"item_ids": [1, 2], "is_predicted_group_percentage": 15.84, "is_relevant_group_percentage": 16.29},
            {"item_ids": [2, 3], "is_predicted_group_percentage": 14.4, "is_relevant_group_percentage": 14.02},
            {"item_ids": [0, 1, 5], "is_predicted_group_percentage": 1.44, "is_relevant_group_percentage": 2.19},
            {"item_ids": [0, 1], "is_predicted_group_percentage": 15.84, "is_relevant_group_percentage": 16.35},
            {"item_ids": [2, 3, 4], "is_predicted_group_percentage": 0.72, "is_relevant_group_percentage": 0.45},
            {"item_ids": [2, 4], "is_predicted_group_percentage": 20.88, "is_relevant_group_percentage": 22.19},
            {"item_ids": [0, 7], "is_predicted_group_percentage": 15.12, "is_relevant_group_percentage": 13.57},
            {"item_ids": [1, 2, 4], "is_predicted_group_percentage": 2.16, "is_relevant_group_percentage": 2.13},
            {"item_ids": [2, 5, 7], "is_predicted_group_percentage": 1.44, "is_relevant_group_percentage": 1.23},
            {"item_ids": [0, 4], "is_predicted_group_percentage": 13.68, "is_relevant_group_percentage": 12.95},
            {"item_ids": [2, 3, 7], "is_predicted_group_percentage": 2.16, "is_relevant_group_percentage": 3.84},
            {"item_ids": [2, 5, 6, 7], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [1, 5], "is_predicted_group_percentage": 12.24, "is_relevant_group_percentage": 10.03},
            {"item_ids": [1, 2, 5], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [0, 2], "is_predicted_group_percentage": 7.2, "is_relevant_group_percentage": 8.54},
            {"item_ids": [4, 7], "is_predicted_group_percentage": 18.0, "is_relevant_group_percentage": 15.44},
            {"item_ids": [1, 3, 7], "is_predicted_group_percentage": 1.44, "is_relevant_group_percentage": 0.64},
            {"item_ids": [0, 5], "is_predicted_group_percentage": 14.4, "is_relevant_group_percentage": 15.12},
            {"item_ids": [0, 6], "is_predicted_group_percentage": 13.68, "is_relevant_group_percentage": 14.02},
            {"item_ids": [1, 3], "is_predicted_group_percentage": 15.12, "is_relevant_group_percentage": 12.35},
            {"item_ids": [3, 5], "is_predicted_group_percentage": 7.2, "is_relevant_group_percentage": 5.86},
            {"item_ids": [4, 5, 7], "is_predicted_group_percentage": 1.44, "is_relevant_group_percentage": 1.28},
            {"item_ids": [2, 4, 7], "is_predicted_group_percentage": 3.6, "is_relevant_group_percentage": 3.6},
            {"item_ids": [3, 6], "is_predicted_group_percentage": 17.28, "is_relevant_group_percentage": 12.4},
            {"item_ids": [3, 7], "is_predicted_group_percentage": 16.56, "is_relevant_group_percentage": 14.19},
            {"item_ids": [2, 7], "is_predicted_group_percentage": 14.4, "is_relevant_group_percentage": 13.57},
            {"item_ids": [0, 2, 5], "is_predicted_group_percentage": 1.44, "is_relevant_group_percentage": 0.77},
            {"item_ids": [5, 6, 7], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [2, 6], "is_predicted_group_percentage": 7.92, "is_relevant_group_percentage": 6.82},
            {"item_ids": [4, 5, 6, 7], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [2, 3, 5], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [1, 3, 5], "is_predicted_group_percentage": 0.72, "is_relevant_group_percentage": 0.91},
            {"item_ids": [1, 2, 5, 7], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [1, 2, 3], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [2, 3, 6], "is_predicted_group_percentage": 0.72, "is_relevant_group_percentage": 0.91},
            {"item_ids": [0, 2, 3], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [2, 4, 5], "is_predicted_group_percentage": 0.72, "is_relevant_group_percentage": 0.32},
            {"item_ids": [1, 7], "is_predicted_group_percentage": 6.48, "is_relevant_group_percentage": 5.92},
            {"item_ids": [0, 2, 3, 4], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [2, 5, 6], "is_predicted_group_percentage": 1.44, "is_relevant_group_percentage": 1.28},
            {"item_ids": [0, 2, 5, 6, 7], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [1, 3, 6, 7], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [3, 4, 6], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [0, 2, 4], "is_predicted_group_percentage": 1.44, "is_relevant_group_percentage": 0.77},
            {"item_ids": [0, 1, 6], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [3, 6, 7], "is_predicted_group_percentage": 1.44, "is_relevant_group_percentage": 0.77},
            {"item_ids": [0, 4, 6], "is_predicted_group_percentage": 1.44, "is_relevant_group_percentage": 0.77},
            {"item_ids": [0, 3, 6], "is_predicted_group_percentage": 1.44, "is_relevant_group_percentage": 1.09},
            {"item_ids": [1, 3, 4], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [0, 4, 7], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [0, 5, 7], "is_predicted_group_percentage": 0.72, "is_relevant_group_percentage": 0.32},
            {"item_ids": [1, 4, 7], "is_predicted_group_percentage": 2.16, "is_relevant_group_percentage": 1.36},
            {"item_ids": [0, 2, 7], "is_predicted_group_percentage": 0.72, "is_relevant_group_percentage": 0.32},
            {"item_ids": [0, 6, 7], "is_predicted_group_percentage": 1.44, "is_relevant_group_percentage": 0.96},
            {"item_ids": [0, 1, 4, 6], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [0, 2, 4, 7], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [0, 1, 2], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [2, 3, 4, 7], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [0, 1, 4], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [3, 4, 7], "is_predicted_group_percentage": 0.72, "is_relevant_group_percentage": 0.45},
            {"item_ids": [0, 3, 7], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [4, 6, 7], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [1, 2, 6], "is_predicted_group_percentage": 1.44, "is_relevant_group_percentage": 0.64},
            {"item_ids": [1, 4, 6, 7], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [0, 2, 6], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [1, 4, 6], "is_predicted_group_percentage": 0.72, "is_relevant_group_percentage": 0.45},
            {"item_ids": [0, 1, 2, 7], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [0, 3, 5, 7], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [1, 5, 6, 7], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [2, 3, 4, 5], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [1, 5, 6], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [2, 6, 7], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0},
            {"item_ids": [1, 5, 7], "is_predicted_group_percentage": 0.0, "is_relevant_group_percentage": 0.0}
        ]
    }
    expected_status = 200
    test_get(uri, expected_result, expected_status)

