"""empty message

Revision ID: 04784aff6b30
Revises: 0f765112e6e9
Create Date: 2018-12-06 12:37:48.016655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04784aff6b30'
down_revision = '0f765112e6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_schedule_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['_schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_scheduled_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('usage_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['_schedule.id'], ),
    sa.ForeignKeyConstraint(['usage_id'], ['_usage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_scheduled_usage')
    op.drop_table('_schedule_day')
    op.drop_table('_schedule')
    # ### end Alembic commands ###
