"""empty message

Revision ID: 0f765112e6e9
Revises: e8dd19776e69
Create Date: 2018-12-05 11:13:03.319933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f765112e6e9'
down_revision = 'e8dd19776e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('_event', 'data_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('_event', sa.Column('data_type', mysql.ENUM('TEMPERATURE', 'WATER_USAGE', 'KILOWATT', 'OTHER', 'value'), nullable=False))
    # ### end Alembic commands ###
