"""empty message

Revision ID: 11381970b25f
Revises: 62a1eef270cd
Create Date: 2018-10-04 11:09:05.851178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11381970b25f'
down_revision = '62a1eef270cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
