"""empty message

Revision ID: 1e1a2fd5cf65
Revises: 1326b214e205
Create Date: 2018-10-16 11:26:00.437058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1a2fd5cf65'
down_revision = '1326b214e205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graph', sa.Column('data_type', sa.Enum('TEMPERATURE', 'WATER_USAGE', 'value', name='datatypeenum'), nullable=True))
    op.add_column('hour', sa.Column('is_final_value', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hour', 'is_final_value')
    op.drop_column('graph', 'data_type')
    # ### end Alembic commands ###
