"""empty message

Revision ID: 321e0eadf7c8
Revises: 1e1a2fd5cf65
Create Date: 2018-10-17 11:13:20.297181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321e0eadf7c8'
down_revision = '1e1a2fd5cf65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('is_module', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'is_module')
    # ### end Alembic commands ###
