"""empty message

Revision ID: 3a311cb361db
Revises: e51bbfefc7fb
Create Date: 2018-11-06 10:03:21.932634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a311cb361db'
down_revision = 'e51bbfefc7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'usage_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('hour', 'value',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hour', 'value',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('event', 'usage_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
