"""empty message

Revision ID: 41642e1dc5be
Revises: 57dc63ee82fe
Create Date: 2018-10-08 13:23:09.309466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41642e1dc5be'
down_revision = '57dc63ee82fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_group')
    # ### end Alembic commands ###
