"""empty message

Revision ID: 46ef1d69403a
Revises: 04784aff6b30
Create Date: 2018-12-12 13:15:32.400981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ef1d69403a'
down_revision = '04784aff6b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_preset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(30), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_preset_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=True),
    sa.Column('usage_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['preset_id'], ['_preset.id'], ),
    sa.ForeignKeyConstraint(['usage_id'], ['_usage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_preset_action')
    op.drop_table('_preset')
    # ### end Alembic commands ###
