"""empty message

Revision ID: 7f86c0a2155a
Revises: 0da94044aecc
Create Date: 2018-11-28 10:55:42.575528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f86c0a2155a'
down_revision = '0da94044aecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('_usage', 'max_value',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('_usage', 'min_value',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('_usage', 'min_value',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('_usage', 'max_value',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
