"""empty message

Revision ID: 9409f42c206a
Revises: 41642e1dc5be
Create Date: 2018-10-08 14:39:53.536086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9409f42c206a'
down_revision = '41642e1dc5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('json', sa.TEXT, nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_call')
    # ### end Alembic commands ###
