"""empty message

Revision ID: e51bbfefc7fb
Revises: 79a8a18080e1
Create Date: 2018-10-17 13:42:29.371039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = 'e51bbfefc7fb'
down_revision = '79a8a18080e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('item_id', sa.Integer(), nullable=True),
                    sa.Column('usage_type', sa.Enum('KILOWATT', 'WATER_PER_HOUR', 'WATER_PER_USAGE', 'value', name='usagetypeenum'), nullable=False),
                    sa.Column('usage', sa.String(255), nullable=False),
                    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
                    sa.PrimaryKeyConstraint('id'))
    op.drop_constraint('event_ibfk_1', 'event', type_='foreignkey')
    op.drop_column('event', 'item_id')
    op.add_column('event', sa.Column('usage_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'event', 'usage', ['usage_id'], ['id'])
    op.drop_column('item', 'usage')
    op.drop_column('item', 'usage_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('usage_type', sa.VARCHAR(length=13), nullable=True))
    op.add_column('item', sa.Column('usage', sa.FLOAT(), nullable=True))
    op.add_column('event', sa.Column('item_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'item', ['item_id'], ['id'])
    op.drop_column('event', 'usage_id')
    op.drop_table('usage')
    # ### end Alembic commands ###
