"""empty message

Revision ID: e5714d1f5b17
Revises: 3a311cb361db
Create Date: 2018-11-20 15:11:15.873281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5714d1f5b17'
down_revision = '3a311cb361db'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('item', sa.Column('control_id', sa.Integer(), nullable=True))
    op.create_table('control',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(255), nullable=False),
                    sa.Column('min', sa.Integer(), nullable=True),
                    sa.Column('max', sa.Integer(), nullable=True),
                    sa.Column('unit', sa.String(255), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    op.create_foreign_key('FK_Item_Control', 'item', 'control', ['control_id'], ['id'], ondelete='SET NULL')




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_table('control')
    op.drop_column('item', 'control_id')
    # ### end Alembic commands ###
