"""empty message

Revision ID: e8dd19776e69
Revises: 7f86c0a2155a
Create Date: 2018-12-04 15:39:23.730159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8dd19776e69'
down_revision = '7f86c0a2155a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('_usage', sa.Column('external_item_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('_usage', 'external_item_id')
    # ### end Alembic commands ###
